// Package public provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package public

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for ProcessInstanceState.
const (
	Active     ProcessInstanceState = "active"
	Completed  ProcessInstanceState = "completed"
	Terminated ProcessInstanceState = "terminated"
)

// Activity defines model for Activity.
type Activity struct {
	BpmnElementType      *string    `json:"bpmnElementType,omitempty"`
	CreatedAt            *time.Time `json:"createdAt,omitempty"`
	ElementId            *string    `json:"elementId,omitempty"`
	Key                  *string    `json:"key,omitempty"`
	ProcessDefinitionKey *string    `json:"processDefinitionKey,omitempty"`
	ProcessInstanceKey   *string    `json:"processInstanceKey,omitempty"`
	State                *string    `json:"state,omitempty"`
}

// ActivityPage defines model for ActivityPage.
type ActivityPage struct {
	// Embedded fields due to inline allOf schema
	Items *[]Activity `json:"items,omitempty"`
	// Embedded struct due to allOf(#/components/schemas/PageMetadata)
	PageMetadata `yaml:",inline"`
}

// Job defines model for Job.
type Job struct {
	CreatedAt          *time.Time `json:"createdAt,omitempty"`
	ElementId          *string    `json:"elementId,omitempty"`
	ElementInstanceKey *string    `json:"elementInstanceKey,omitempty"`
	Key                *string    `json:"key,omitempty"`
	ProcessInstanceKey *string    `json:"processInstanceKey,omitempty"`
	State              *string    `json:"state,omitempty"`
}

// JobPage defines model for JobPage.
type JobPage struct {
	// Embedded fields due to inline allOf schema
	Items *[]Job `json:"items,omitempty"`
	// Embedded struct due to allOf(#/components/schemas/PageMetadata)
	PageMetadata `yaml:",inline"`
}

// PageMetadata defines model for PageMetadata.
type PageMetadata struct {
	Count  *int `json:"count,omitempty"`
	Offset *int `json:"offset,omitempty"`
	Size   *int `json:"size,omitempty"`
}

// ProcessDefinitionDetail defines model for ProcessDefinitionDetail.
type ProcessDefinitionDetail struct {
	// Embedded struct due to allOf(#/components/schemas/ProcessDefinitionSimple)
	ProcessDefinitionSimple `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	BpmnData *string `json:"bpmnData,omitempty"`
}

// ProcessDefinitionSimple defines model for ProcessDefinitionSimple.
type ProcessDefinitionSimple struct {
	BpmnProcessId *string `json:"bpmnProcessId,omitempty"`
	Key           *string `json:"key,omitempty"`
	Version       *int    `json:"version,omitempty"`
}

// ProcessDefinitionsPage defines model for ProcessDefinitionsPage.
type ProcessDefinitionsPage struct {
	// Embedded fields due to inline allOf schema
	Items *[]ProcessDefinitionSimple `json:"items,omitempty"`
	// Embedded struct due to allOf(#/components/schemas/PageMetadata)
	PageMetadata `yaml:",inline"`
}

// ProcessInstance defines model for ProcessInstance.
type ProcessInstance struct {
	Activities           *string               `json:"activities,omitempty"`
	CaughtEvents         *string               `json:"caughtEvents,omitempty"`
	CreatedAt            *time.Time            `json:"createdAt,omitempty"`
	Key                  *string               `json:"key,omitempty"`
	ProcessDefinitionKey *string               `json:"processDefinitionKey,omitempty"`
	State                *ProcessInstanceState `json:"state,omitempty"`
	VariableHolder       *string               `json:"variableHolder,omitempty"`
}

// ProcessInstanceState defines model for ProcessInstance.State.
type ProcessInstanceState string

// ProcessInstancePage defines model for ProcessInstancePage.
type ProcessInstancePage struct {
	// Embedded fields due to inline allOf schema
	Items *[]ProcessInstance `json:"items,omitempty"`
	// Embedded struct due to allOf(#/components/schemas/PageMetadata)
	PageMetadata `yaml:",inline"`
}

// CompleteJobJSONBody defines parameters for CompleteJob.
type CompleteJobJSONBody struct {
	JobKey string `json:"jobKey"`
}

// CreateProcessInstanceJSONBody defines parameters for CreateProcessInstance.
type CreateProcessInstanceJSONBody struct {
	ProcessDefinitionKey string                  `json:"processDefinitionKey"`
	Variables            *map[string]interface{} `json:"variables,omitempty"`
}

// GetProcessInstancesParams defines parameters for GetProcessInstances.
type GetProcessInstancesParams struct {
	ProcessDefinitionKey *int64 `form:"processDefinitionKey,omitempty" json:"processDefinitionKey,omitempty"`
	Offset               *int   `form:"offset,omitempty" json:"offset,omitempty"`
	Size                 *int   `form:"size,omitempty" json:"size,omitempty"`
}

// CompleteJobJSONRequestBody defines body for CompleteJob for application/json ContentType.
type CompleteJobJSONRequestBody CompleteJobJSONBody

// CreateProcessInstanceJSONRequestBody defines body for CreateProcessInstance for application/json ContentType.
type CreateProcessInstanceJSONRequestBody CreateProcessInstanceJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Complete a job
	// (POST /jobs)
	CompleteJob(w http.ResponseWriter, r *http.Request)
	// Get list of process definitions
	// (GET /process-definitions)
	GetProcessDefinitions(w http.ResponseWriter, r *http.Request)
	// Deploy a new process definition
	// (POST /process-definitions)
	CreateProcessDefinition(w http.ResponseWriter, r *http.Request)
	// Get process definition
	// (GET /process-definitions/{processDefinitionKey})
	GetProcessDefinition(w http.ResponseWriter, r *http.Request, processDefinitionKey int64)
	// Create a new process instance
	// (POST /process-instances)
	CreateProcessInstance(w http.ResponseWriter, r *http.Request)
	// Get list of running process instances
	// (GET /process-instances/)
	GetProcessInstances(w http.ResponseWriter, r *http.Request, params GetProcessInstancesParams)
	// Get state of a process instance selected by processInstanceId
	// (GET /process-instances/{processInstanceKey})
	GetProcessInstance(w http.ResponseWriter, r *http.Request, processInstanceKey int64)
	// Get list of activities for a process instance
	// (GET /process-instances/{processInstanceKey}/activities)
	GetActivities(w http.ResponseWriter, r *http.Request, processInstanceKey int64)
	// Get list of jobs for a process instance
	// (GET /process-instances/{processInstanceKey}/jobs)
	GetJobs(w http.ResponseWriter, r *http.Request, processInstanceKey int64)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Complete a job
// (POST /jobs)
func (_ Unimplemented) CompleteJob(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get list of process definitions
// (GET /process-definitions)
func (_ Unimplemented) GetProcessDefinitions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Deploy a new process definition
// (POST /process-definitions)
func (_ Unimplemented) CreateProcessDefinition(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get process definition
// (GET /process-definitions/{processDefinitionKey})
func (_ Unimplemented) GetProcessDefinition(w http.ResponseWriter, r *http.Request, processDefinitionKey int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new process instance
// (POST /process-instances)
func (_ Unimplemented) CreateProcessInstance(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get list of running process instances
// (GET /process-instances/)
func (_ Unimplemented) GetProcessInstances(w http.ResponseWriter, r *http.Request, params GetProcessInstancesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get state of a process instance selected by processInstanceId
// (GET /process-instances/{processInstanceKey})
func (_ Unimplemented) GetProcessInstance(w http.ResponseWriter, r *http.Request, processInstanceKey int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get list of activities for a process instance
// (GET /process-instances/{processInstanceKey}/activities)
func (_ Unimplemented) GetActivities(w http.ResponseWriter, r *http.Request, processInstanceKey int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get list of jobs for a process instance
// (GET /process-instances/{processInstanceKey}/jobs)
func (_ Unimplemented) GetJobs(w http.ResponseWriter, r *http.Request, processInstanceKey int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CompleteJob operation middleware
func (siw *ServerInterfaceWrapper) CompleteJob(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteJob(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetProcessDefinitions operation middleware
func (siw *ServerInterfaceWrapper) GetProcessDefinitions(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProcessDefinitions(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateProcessDefinition operation middleware
func (siw *ServerInterfaceWrapper) CreateProcessDefinition(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProcessDefinition(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetProcessDefinition operation middleware
func (siw *ServerInterfaceWrapper) GetProcessDefinition(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "processDefinitionKey" -------------
	var processDefinitionKey int64

	err = runtime.BindStyledParameterWithOptions("simple", "processDefinitionKey", chi.URLParam(r, "processDefinitionKey"), &processDefinitionKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "processDefinitionKey", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProcessDefinition(w, r, processDefinitionKey)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateProcessInstance operation middleware
func (siw *ServerInterfaceWrapper) CreateProcessInstance(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProcessInstance(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetProcessInstances operation middleware
func (siw *ServerInterfaceWrapper) GetProcessInstances(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProcessInstancesParams

	// ------------- Optional query parameter "processDefinitionKey" -------------

	err = runtime.BindQueryParameter("form", true, false, "processDefinitionKey", r.URL.Query(), &params.ProcessDefinitionKey)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "processDefinitionKey", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameter("form", true, false, "size", r.URL.Query(), &params.Size)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "size", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProcessInstances(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetProcessInstance operation middleware
func (siw *ServerInterfaceWrapper) GetProcessInstance(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "processInstanceKey" -------------
	var processInstanceKey int64

	err = runtime.BindStyledParameterWithOptions("simple", "processInstanceKey", chi.URLParam(r, "processInstanceKey"), &processInstanceKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "processInstanceKey", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProcessInstance(w, r, processInstanceKey)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetActivities operation middleware
func (siw *ServerInterfaceWrapper) GetActivities(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "processInstanceKey" -------------
	var processInstanceKey int64

	err = runtime.BindStyledParameterWithOptions("simple", "processInstanceKey", chi.URLParam(r, "processInstanceKey"), &processInstanceKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "processInstanceKey", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetActivities(w, r, processInstanceKey)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetJobs operation middleware
func (siw *ServerInterfaceWrapper) GetJobs(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "processInstanceKey" -------------
	var processInstanceKey int64

	err = runtime.BindStyledParameterWithOptions("simple", "processInstanceKey", chi.URLParam(r, "processInstanceKey"), &processInstanceKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "processInstanceKey", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJobs(w, r, processInstanceKey)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/jobs", wrapper.CompleteJob)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/process-definitions", wrapper.GetProcessDefinitions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/process-definitions", wrapper.CreateProcessDefinition)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/process-definitions/{processDefinitionKey}", wrapper.GetProcessDefinition)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/process-instances", wrapper.CreateProcessInstance)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/process-instances/", wrapper.GetProcessInstances)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/process-instances/{processInstanceKey}", wrapper.GetProcessInstance)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/process-instances/{processInstanceKey}/activities", wrapper.GetActivities)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/process-instances/{processInstanceKey}/jobs", wrapper.GetJobs)
	})

	return r
}

type CompleteJobRequestObject struct {
	Body *CompleteJobJSONRequestBody
}

type CompleteJobResponseObject interface {
	VisitCompleteJobResponse(w http.ResponseWriter) error
}

type CompleteJob201Response struct {
}

func (response CompleteJob201Response) VisitCompleteJobResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type GetProcessDefinitionsRequestObject struct {
}

type GetProcessDefinitionsResponseObject interface {
	VisitGetProcessDefinitionsResponse(w http.ResponseWriter) error
}

type GetProcessDefinitions200JSONResponse ProcessDefinitionsPage

func (response GetProcessDefinitions200JSONResponse) VisitGetProcessDefinitionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateProcessDefinitionRequestObject struct {
	Body io.Reader
}

type CreateProcessDefinitionResponseObject interface {
	VisitCreateProcessDefinitionResponse(w http.ResponseWriter) error
}

type CreateProcessDefinition200JSONResponse struct {
	ProcessDefinitionKey *string `json:"processDefinitionKey,omitempty"`
}

func (response CreateProcessDefinition200JSONResponse) VisitCreateProcessDefinitionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProcessDefinitionRequestObject struct {
	ProcessDefinitionKey int64 `json:"processDefinitionKey"`
}

type GetProcessDefinitionResponseObject interface {
	VisitGetProcessDefinitionResponse(w http.ResponseWriter) error
}

type GetProcessDefinition200JSONResponse ProcessDefinitionDetail

func (response GetProcessDefinition200JSONResponse) VisitGetProcessDefinitionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateProcessInstanceRequestObject struct {
	Body *CreateProcessInstanceJSONRequestBody
}

type CreateProcessInstanceResponseObject interface {
	VisitCreateProcessInstanceResponse(w http.ResponseWriter) error
}

type CreateProcessInstance200JSONResponse ProcessInstance

func (response CreateProcessInstance200JSONResponse) VisitCreateProcessInstanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProcessInstancesRequestObject struct {
	Params GetProcessInstancesParams
}

type GetProcessInstancesResponseObject interface {
	VisitGetProcessInstancesResponse(w http.ResponseWriter) error
}

type GetProcessInstances200JSONResponse struct {
	ProcessInstances *[]ProcessInstancePage `json:"processInstances,omitempty"`
	Total            *int                   `json:"total,omitempty"`
}

func (response GetProcessInstances200JSONResponse) VisitGetProcessInstancesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProcessInstanceRequestObject struct {
	ProcessInstanceKey int64 `json:"processInstanceKey"`
}

type GetProcessInstanceResponseObject interface {
	VisitGetProcessInstanceResponse(w http.ResponseWriter) error
}

type GetProcessInstance200JSONResponse ProcessInstance

func (response GetProcessInstance200JSONResponse) VisitGetProcessInstanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetActivitiesRequestObject struct {
	ProcessInstanceKey int64 `json:"processInstanceKey"`
}

type GetActivitiesResponseObject interface {
	VisitGetActivitiesResponse(w http.ResponseWriter) error
}

type GetActivities200JSONResponse ActivityPage

func (response GetActivities200JSONResponse) VisitGetActivitiesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetJobsRequestObject struct {
	ProcessInstanceKey int64 `json:"processInstanceKey"`
}

type GetJobsResponseObject interface {
	VisitGetJobsResponse(w http.ResponseWriter) error
}

type GetJobs200JSONResponse JobPage

func (response GetJobs200JSONResponse) VisitGetJobsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Complete a job
	// (POST /jobs)
	CompleteJob(ctx context.Context, request CompleteJobRequestObject) (CompleteJobResponseObject, error)
	// Get list of process definitions
	// (GET /process-definitions)
	GetProcessDefinitions(ctx context.Context, request GetProcessDefinitionsRequestObject) (GetProcessDefinitionsResponseObject, error)
	// Deploy a new process definition
	// (POST /process-definitions)
	CreateProcessDefinition(ctx context.Context, request CreateProcessDefinitionRequestObject) (CreateProcessDefinitionResponseObject, error)
	// Get process definition
	// (GET /process-definitions/{processDefinitionKey})
	GetProcessDefinition(ctx context.Context, request GetProcessDefinitionRequestObject) (GetProcessDefinitionResponseObject, error)
	// Create a new process instance
	// (POST /process-instances)
	CreateProcessInstance(ctx context.Context, request CreateProcessInstanceRequestObject) (CreateProcessInstanceResponseObject, error)
	// Get list of running process instances
	// (GET /process-instances/)
	GetProcessInstances(ctx context.Context, request GetProcessInstancesRequestObject) (GetProcessInstancesResponseObject, error)
	// Get state of a process instance selected by processInstanceId
	// (GET /process-instances/{processInstanceKey})
	GetProcessInstance(ctx context.Context, request GetProcessInstanceRequestObject) (GetProcessInstanceResponseObject, error)
	// Get list of activities for a process instance
	// (GET /process-instances/{processInstanceKey}/activities)
	GetActivities(ctx context.Context, request GetActivitiesRequestObject) (GetActivitiesResponseObject, error)
	// Get list of jobs for a process instance
	// (GET /process-instances/{processInstanceKey}/jobs)
	GetJobs(ctx context.Context, request GetJobsRequestObject) (GetJobsResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CompleteJob operation middleware
func (sh *strictHandler) CompleteJob(w http.ResponseWriter, r *http.Request) {
	var request CompleteJobRequestObject

	var body CompleteJobJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteJob(ctx, request.(CompleteJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CompleteJobResponseObject); ok {
		if err := validResponse.VisitCompleteJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProcessDefinitions operation middleware
func (sh *strictHandler) GetProcessDefinitions(w http.ResponseWriter, r *http.Request) {
	var request GetProcessDefinitionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProcessDefinitions(ctx, request.(GetProcessDefinitionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProcessDefinitions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProcessDefinitionsResponseObject); ok {
		if err := validResponse.VisitGetProcessDefinitionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProcessDefinition operation middleware
func (sh *strictHandler) CreateProcessDefinition(w http.ResponseWriter, r *http.Request) {
	var request CreateProcessDefinitionRequestObject

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProcessDefinition(ctx, request.(CreateProcessDefinitionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProcessDefinition")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateProcessDefinitionResponseObject); ok {
		if err := validResponse.VisitCreateProcessDefinitionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProcessDefinition operation middleware
func (sh *strictHandler) GetProcessDefinition(w http.ResponseWriter, r *http.Request, processDefinitionKey int64) {
	var request GetProcessDefinitionRequestObject

	request.ProcessDefinitionKey = processDefinitionKey

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProcessDefinition(ctx, request.(GetProcessDefinitionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProcessDefinition")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProcessDefinitionResponseObject); ok {
		if err := validResponse.VisitGetProcessDefinitionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProcessInstance operation middleware
func (sh *strictHandler) CreateProcessInstance(w http.ResponseWriter, r *http.Request) {
	var request CreateProcessInstanceRequestObject

	var body CreateProcessInstanceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProcessInstance(ctx, request.(CreateProcessInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProcessInstance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateProcessInstanceResponseObject); ok {
		if err := validResponse.VisitCreateProcessInstanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProcessInstances operation middleware
func (sh *strictHandler) GetProcessInstances(w http.ResponseWriter, r *http.Request, params GetProcessInstancesParams) {
	var request GetProcessInstancesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProcessInstances(ctx, request.(GetProcessInstancesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProcessInstances")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProcessInstancesResponseObject); ok {
		if err := validResponse.VisitGetProcessInstancesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProcessInstance operation middleware
func (sh *strictHandler) GetProcessInstance(w http.ResponseWriter, r *http.Request, processInstanceKey int64) {
	var request GetProcessInstanceRequestObject

	request.ProcessInstanceKey = processInstanceKey

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProcessInstance(ctx, request.(GetProcessInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProcessInstance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProcessInstanceResponseObject); ok {
		if err := validResponse.VisitGetProcessInstanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetActivities operation middleware
func (sh *strictHandler) GetActivities(w http.ResponseWriter, r *http.Request, processInstanceKey int64) {
	var request GetActivitiesRequestObject

	request.ProcessInstanceKey = processInstanceKey

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetActivities(ctx, request.(GetActivitiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetActivities")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetActivitiesResponseObject); ok {
		if err := validResponse.VisitGetActivitiesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJobs operation middleware
func (sh *strictHandler) GetJobs(w http.ResponseWriter, r *http.Request, processInstanceKey int64) {
	var request GetJobsRequestObject

	request.ProcessInstanceKey = processInstanceKey

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJobs(ctx, request.(GetJobsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJobs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJobsResponseObject); ok {
		if err := validResponse.VisitGetJobsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xYT2/jthP9KgJ/v6MTKW1RLHTzNsHWabdrNHtb+EBJI5teitSSI7eu4e9ekJKtf5Qj",
	"O05Q7MkyORpy3pt5Q2pHYpnlUoBATcId0fEKMmofpzGyDcOtec6VzEEhAzsT5Zl44JCBwM/bHMwQ2l+i",
	"UTGxJPsJiRVQhGSKZjaVKqNIQpJQhBtkGZBJ/xUoXc4Sp8OvsHWO50rGoPU9pEwwZFL8dtpwJjRSEcOQ",
	"mUaKrpD2xx3LaA0xGtsDRHO6tK9Qzj+lJPzSBYwhZO2H/ytISUj+59fw+xX2/hH4ekmqFN0693DaldnY",
	"R0CaUKRkv3CE8CijPsFXJ+8w+wz2X9+OukcZXZc1A+RbENay6DMnC4ENCJhAWIIyL8o01TAwp9k/4Jpx",
	"ITfvFtw9IGW8jeTJGLsOnliWc7DY9IXmvorzWU4XY/ZaLeWUtMr4TP3ZgNJMiovR09dNw2Fw3yA122Xa",
	"R5mWylb96/cMWixX+LA5NKNrNJUXt42jqIAoMhJ+KYMwaxmMOCAkZl1QGRNmc2Th2MWGKkYjDr9KnoAa",
	"KVEdOF8lT45cvX5+GI9MpNLsLAEdK5ajLRzy58PTZ286n3mpVB5n0Y2pxhsQSyYspwxNyZL3849/eA92",
	"1PuUg5jOZ6RRfyS4vbsNrNLlIGjOSEh+vA1uAzIhOcWVhcRfy8g+5FLbLDIIUrMPU/bkl4pSI+YTouBb",
	"ARrfy2RbaqtAKNWV5jlnsX3PX+uy+ksc+km/lpE7t/blCkxBYvKqsnMDVxuiKsAO6FwKXS7xQ3DXR/VR",
	"Rl6dosaJLrKMqm0jTo96axsq0qWuNqHJwhj7VYXcJLVUmUWW4MDtA2Bf2Ehvl8FZMJ4lc6WMWqzaMPzO",
	"NHoy9apwvGY4bVA+AHr8hHWNkguahREVd1JZ1erteHSC/Z3xNjBH5TMzPbUZky7BC/J5pHLunXnc5mbe",
	"Q9lLIOdy20vYezvsUU/AXw5ynuVmIKH9nSua/Vl5buVF0QwQlLa6zExsRnLIhAiaGQycoHV5mrg4ZgJ/",
	"/qlmuT5cLN6yvKoz3igOHWX1QsZY1aVOKXezyI5d7VoaPvq0cGj0zfPLMf/beu/0eZn6X534+lgwTPiB",
	"FK86lXVbjB3tVCyriemyX3M8wL0/oipnRyfuovxWgNo+W5XnVOHE7bm6bDV9JZDSgiMJg/Fu7L3M6eQu",
	"eAVJcCb9rFl8l5wty87cPV9OCEqkfNy9abitq0IIJpa9DDvV3IffuSQtd/2vE/szUvWc9tH8APKfbx6n",
	"NOTJXKoMFbQvDX3e9LC1p4FDjJB40dbroDRLrsan3765DlE7ra2+O1Zb3zpPFGQDqeEKrI3snY9ep0E4",
	"mTtc+IY4ezTz3x1bh8+bJ4iywAxTZKYvJMf4BLU5YFkoTkKyQsxD3+cypnwlNYbvgndB+Z2g9LXrAN06",
	"D5oG2ZluKP1i/28AAAD//5Kf7nLIGAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
