// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ProcessInstanceState.
const (
	Active     ProcessInstanceState = "active"
	Completed  ProcessInstanceState = "completed"
	Terminated ProcessInstanceState = "terminated"
)

// Activity defines model for Activity.
type Activity struct {
	BpmnElementType      *string    `json:"bpmnElementType,omitempty"`
	CreatedAt            *time.Time `json:"createdAt,omitempty"`
	ElementId            *string    `json:"elementId,omitempty"`
	Key                  *string    `json:"key,omitempty"`
	ProcessDefinitionKey *string    `json:"processDefinitionKey,omitempty"`
	ProcessInstanceKey   *string    `json:"processInstanceKey,omitempty"`
	State                *string    `json:"state,omitempty"`
}

// ActivityPage defines model for ActivityPage.
type ActivityPage struct {
	Count  *int        `json:"count,omitempty"`
	Items  *[]Activity `json:"items,omitempty"`
	Offset *int        `json:"offset,omitempty"`
	Size   *int        `json:"size,omitempty"`
}

// Job defines model for Job.
type Job struct {
	CreatedAt          *time.Time `json:"createdAt,omitempty"`
	ElementId          *string    `json:"elementId,omitempty"`
	ElementInstanceKey *string    `json:"elementInstanceKey,omitempty"`
	Key                *string    `json:"key,omitempty"`
	ProcessInstanceKey *string    `json:"processInstanceKey,omitempty"`
	State              *string    `json:"state,omitempty"`
}

// JobPage defines model for JobPage.
type JobPage struct {
	Count  *int   `json:"count,omitempty"`
	Items  *[]Job `json:"items,omitempty"`
	Offset *int   `json:"offset,omitempty"`
	Size   *int   `json:"size,omitempty"`
}

// PageMetadata defines model for PageMetadata.
type PageMetadata struct {
	Count  *int `json:"count,omitempty"`
	Offset *int `json:"offset,omitempty"`
	Size   *int `json:"size,omitempty"`
}

// ProcessDefinitionDetail defines model for ProcessDefinitionDetail.
type ProcessDefinitionDetail struct {
	BpmnData      *string `json:"bpmnData,omitempty"`
	BpmnProcessId *string `json:"bpmnProcessId,omitempty"`
	Key           *string `json:"key,omitempty"`
	Version       *int    `json:"version,omitempty"`
}

// ProcessDefinitionSimple defines model for ProcessDefinitionSimple.
type ProcessDefinitionSimple struct {
	BpmnProcessId *string `json:"bpmnProcessId,omitempty"`
	Key           *string `json:"key,omitempty"`
	Version       *int    `json:"version,omitempty"`
}

// ProcessDefinitionsPage defines model for ProcessDefinitionsPage.
type ProcessDefinitionsPage struct {
	Count  *int                       `json:"count,omitempty"`
	Items  *[]ProcessDefinitionSimple `json:"items,omitempty"`
	Offset *int                       `json:"offset,omitempty"`
	Size   *int                       `json:"size,omitempty"`
}

// ProcessInstance defines model for ProcessInstance.
type ProcessInstance struct {
	Activities           *string               `json:"activities,omitempty"`
	CaughtEvents         *string               `json:"caughtEvents,omitempty"`
	CreatedAt            *time.Time            `json:"createdAt,omitempty"`
	Key                  *string               `json:"key,omitempty"`
	ProcessDefinitionKey *string               `json:"processDefinitionKey,omitempty"`
	State                *ProcessInstanceState `json:"state,omitempty"`
	VariableHolder       *string               `json:"variableHolder,omitempty"`
}

// ProcessInstanceState defines model for ProcessInstance.State.
type ProcessInstanceState string

// ProcessInstancePage defines model for ProcessInstancePage.
type ProcessInstancePage struct {
	Count  *int               `json:"count,omitempty"`
	Items  *[]ProcessInstance `json:"items,omitempty"`
	Offset *int               `json:"offset,omitempty"`
	Size   *int               `json:"size,omitempty"`
}

// CompleteJobJSONBody defines parameters for CompleteJob.
type CompleteJobJSONBody struct {
	JobKey string `json:"jobKey"`
}

// CreateProcessInstanceJSONBody defines parameters for CreateProcessInstance.
type CreateProcessInstanceJSONBody struct {
	ProcessDefinitionKey string                  `json:"processDefinitionKey"`
	Variables            *map[string]interface{} `json:"variables,omitempty"`
}

// GetProcessInstancesParams defines parameters for GetProcessInstances.
type GetProcessInstancesParams struct {
	ProcessDefinitionKey *int64 `form:"processDefinitionKey,omitempty" json:"processDefinitionKey,omitempty"`
	Offset               *int   `form:"offset,omitempty" json:"offset,omitempty"`
	Size                 *int   `form:"size,omitempty" json:"size,omitempty"`
}

// CompleteJobJSONRequestBody defines body for CompleteJob for application/json ContentType.
type CompleteJobJSONRequestBody CompleteJobJSONBody

// CreateProcessInstanceJSONRequestBody defines body for CreateProcessInstance for application/json ContentType.
type CreateProcessInstanceJSONRequestBody CreateProcessInstanceJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Complete a job
	// (POST /jobs)
	CompleteJob(ctx echo.Context) error
	// Get list of process definitions
	// (GET /process-definitions)
	GetProcessDefinitions(ctx echo.Context) error
	// Deploy a new process definition
	// (POST /process-definitions)
	CreateProcessDefinition(ctx echo.Context) error
	// Get process definition
	// (GET /process-definitions/{processDefinitionKey})
	GetProcessDefinition(ctx echo.Context, processDefinitionKey int64) error
	// Create a new process instance
	// (POST /process-instances)
	CreateProcessInstance(ctx echo.Context) error
	// Get list of running process instances
	// (GET /process-instances/)
	GetProcessInstances(ctx echo.Context, params GetProcessInstancesParams) error
	// Get state of a process instance selected by processInstanceId
	// (GET /process-instances/{processInstanceKey})
	GetProcessInstance(ctx echo.Context, processInstanceKey int64) error
	// Get list of activities for a process instance
	// (GET /process-instances/{processInstanceKey}/activities)
	GetActivities(ctx echo.Context, processInstanceKey int64) error
	// Get list of jobs for a process instance
	// (GET /process-instances/{processInstanceKey}/jobs)
	GetJobs(ctx echo.Context, processInstanceKey int64) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CompleteJob converts echo context to params.
func (w *ServerInterfaceWrapper) CompleteJob(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CompleteJob(ctx)
	return err
}

// GetProcessDefinitions converts echo context to params.
func (w *ServerInterfaceWrapper) GetProcessDefinitions(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProcessDefinitions(ctx)
	return err
}

// CreateProcessDefinition converts echo context to params.
func (w *ServerInterfaceWrapper) CreateProcessDefinition(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateProcessDefinition(ctx)
	return err
}

// GetProcessDefinition converts echo context to params.
func (w *ServerInterfaceWrapper) GetProcessDefinition(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "processDefinitionKey" -------------
	var processDefinitionKey int64

	err = runtime.BindStyledParameterWithOptions("simple", "processDefinitionKey", ctx.Param("processDefinitionKey"), &processDefinitionKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter processDefinitionKey: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProcessDefinition(ctx, processDefinitionKey)
	return err
}

// CreateProcessInstance converts echo context to params.
func (w *ServerInterfaceWrapper) CreateProcessInstance(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateProcessInstance(ctx)
	return err
}

// GetProcessInstances converts echo context to params.
func (w *ServerInterfaceWrapper) GetProcessInstances(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProcessInstancesParams
	// ------------- Optional query parameter "processDefinitionKey" -------------

	err = runtime.BindQueryParameter("form", true, false, "processDefinitionKey", ctx.QueryParams(), &params.ProcessDefinitionKey)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter processDefinitionKey: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameter("form", true, false, "size", ctx.QueryParams(), &params.Size)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter size: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProcessInstances(ctx, params)
	return err
}

// GetProcessInstance converts echo context to params.
func (w *ServerInterfaceWrapper) GetProcessInstance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "processInstanceKey" -------------
	var processInstanceKey int64

	err = runtime.BindStyledParameterWithOptions("simple", "processInstanceKey", ctx.Param("processInstanceKey"), &processInstanceKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter processInstanceKey: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProcessInstance(ctx, processInstanceKey)
	return err
}

// GetActivities converts echo context to params.
func (w *ServerInterfaceWrapper) GetActivities(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "processInstanceKey" -------------
	var processInstanceKey int64

	err = runtime.BindStyledParameterWithOptions("simple", "processInstanceKey", ctx.Param("processInstanceKey"), &processInstanceKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter processInstanceKey: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetActivities(ctx, processInstanceKey)
	return err
}

// GetJobs converts echo context to params.
func (w *ServerInterfaceWrapper) GetJobs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "processInstanceKey" -------------
	var processInstanceKey int64

	err = runtime.BindStyledParameterWithOptions("simple", "processInstanceKey", ctx.Param("processInstanceKey"), &processInstanceKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter processInstanceKey: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetJobs(ctx, processInstanceKey)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/jobs", wrapper.CompleteJob)
	router.GET(baseURL+"/process-definitions", wrapper.GetProcessDefinitions)
	router.POST(baseURL+"/process-definitions", wrapper.CreateProcessDefinition)
	router.GET(baseURL+"/process-definitions/:processDefinitionKey", wrapper.GetProcessDefinition)
	router.POST(baseURL+"/process-instances", wrapper.CreateProcessInstance)
	router.GET(baseURL+"/process-instances/", wrapper.GetProcessInstances)
	router.GET(baseURL+"/process-instances/:processInstanceKey", wrapper.GetProcessInstance)
	router.GET(baseURL+"/process-instances/:processInstanceKey/activities", wrapper.GetActivities)
	router.GET(baseURL+"/process-instances/:processInstanceKey/jobs", wrapper.GetJobs)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xYT2/jthP9KgJ/v6MTKW1RLHTzNsHWabdrNHtb+EBJI5teitSSI7eu4e9ekJKtf5Qj",
	"O05Q7MkyORpy3pt5Q2pHYpnlUoBATcId0fEKMmofpzGyDcOtec6VzEEhAzsT5Zl44JCBwM/bHMwQ2l+i",
	"UTGxJPsJiRVQhGSKZjaVKqNIQpJQhBtkGZBJ/xUoXc4Sp8OvsHWO50rGoPU9pEwwZFL8dtpwJjRSEcOQ",
	"mUaKrpD2xx3LaA0xGtsDRHO6tK9Qzj+lJPzSBYwhZO2H/ytISUj+59fw+xX2/hH4ekmqFN0693DaldnY",
	"R0CaUKRkv3CE8CijPsFXJ+8w+wz2X9+OukcZXZc1A+RbENay6DMnC4ENCJhAWIIyL8o01TAwp9k/4Jpx",
	"ITfvFtw9IGW8jeTJGLsOnliWc7DY9IXmvorzWU4XY/ZaLeWUtMr4TP3ZgNJMiovR09dNw2Fw3yA122Xa",
	"R5mWylb96/cMWixX+LA5NKNrNJUXt42jqIAoMhJ+KYMwaxmMOCAkZl1QGRNmc2Th2MWGKkYjDr9KnoAa",
	"KVEdOF8lT45cvX5+GI9MpNLsLAEdK5ajLRzy58PTZ286n3mpVB5n0Y2pxhsQSyYspwxNyZL3849/eA92",
	"1PuUg5jOZ6RRfyS4vbsNrNLlIGjOSEh+vA1uAzIhOcWVhcRfy8g+5FLbLDIIUrMPU/bkl4pSI+YTouBb",
	"ARrfy2RbaqtAKNWV5jlnsX3PX+uy+ksc+km/lpE7t/blCkxBYvKqsnMDVxuiKsAO6FwKXS7xQ3DXR/VR",
	"Rl6dosaJLrKMqm0jTo96axsq0qWuNqHJwhj7VYXcJLVUmUWW4MDtA2Bf2Ehvl8FZMJ4lc6WMWqzaMPzO",
	"NHoy9apwvGY4bVA+AHr8hHWNkguahREVd1JZ1erteHSC/Z3xNjBH5TMzPbUZky7BC/J5pHLunXnc5mbe",
	"Q9lLIOdy20vYezvsUU/AXw5ynuVmIKH9nSua/Vl5buVF0QwQlLa6zExsRnLIhAiaGQycoHV5mrg4ZgJ/",
	"/qlmuT5cLN6yvKoz3igOHWX1QsZY1aVOKXezyI5d7VoaPvq0cGj0zfPLMf/beu/0eZn6X534+lgwTPiB",
	"FK86lXVbjB3tVCyriemyX3M8wL0/oipnRyfuovxWgNo+W5XnVOHE7bm6bDV9JZDSgiMJg/Fu7L3M6eQu",
	"eAVJcCb9rFl8l5wty87cPV9OCEqkfNy9abitq0IIJpa9DDvV3IffuSQtd/2vE/szUvWc9tH8APKfbx6n",
	"NOTJXKoMFbQvDX3e9LC1p4FDjJB40dbroDRLrsan3765DlE7ra2+O1Zb3zpPFGQDqeEKrI3snY9ep0E4",
	"mTtc+IY4ezTz3x1bh8+bJ4iywAxTZKYvJMf4BLU5YFkoTkKyQsxD3+cypnwlNYbvgndB+Z2g9LXrAN06",
	"D5oG2ZluKP1i/28AAAD//5Kf7nLIGAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
